version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/Super-Mario-3d-World-Mod-Downloader"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: C-Sharp
