name: .NET

on:
  push:
    branches: [ C-Sharp ]
  pull_request:
    branches: [ C-Sharp ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy Files
      run: copy Super-Mario-3d-World-Mod-Downloader\bin\Release\Super-Mario-3d-World-Mod-Downloader.exe %CD% && copy Super-Mario-3d-World-Mod-Downloader\bin\Release\SM3DW-Keys.dll %CD%
    - name : Zip Files
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a Release.zip Super-Mario-3d-World-Mod-Downloader.exe SM3DW-Keys.dll
    - uses: actions/upload-artifact@v2
      with:
        name: Release
        path: Release.zip